server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt?serverTimezone=Asia/Seoul
    username: root
    password: 0414

  jpa:
    properties:
      hibernate:
        ddl-auto: update # ??: update, create, create-drop, none
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    naming:
      physical:
        strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  jwt:
    expiration_time: 86400000 # 24h
    secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

logging:
  level:
    org.hibernate.SQL: DEBUG